sudo: false
language: node_js
node_js:
  - '7'
  - '6'
  - '4'
  - "0.12"

before_install:
  - npm install -g npm

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run ci-tests
